### PR TITLE
New syntax for rt-require: "import" "from"

### PR DESCRIPTION
**Pull request by nippur72**
This PR introduces a new cleaner syntax for `rt-require` that allows to import specific members from modules instead of importing the whole module. The syntax is inspired by the ES6 import statement.

The old syntax with `dependency` and `as` is still available but a deprecated warning is emitted encouraging the user to migrate to the new syntax.

How to use it:
```html
<rt-require import="foo" from="mylib" />
<rt-require import="foo as myfoo" from="mylib" />
<rt-require import="* as myfoo" from="mylib" />
<rt-require import="default as myfoo" from="mylib" />
```
which translates respectively to:
```ts
// es6
import {foo} from "mylib";
import {foo as myfoo} from "mylib";
import * as myfoo from "mylib";
import myfoo from "mylib";

// commonjs
var foo = require("mylib").foo;
var myfoo = require("mylib").foo;
var myfoo = require("mylib");
var myfoo = require("mylib").default;
```

### CODE REVIEW

**Comment by ganimomer** [comment]
This definitely seems like a much-needed feature, but we're a bit concerned about using `rt-require` for it.
First of all, the idea of keeping both options on the same tag seems confusing, but also, the `require` part of `rt-require` is supposed to mimic CommonJS and AMD's `require`s.

The solution we think is best would be to allow a new attribute, `rt-import` which has this syntax which is similar to ES6 modules, but separates the declaration to `name` and `as` attributes, where the `as` is optional. (`<rt-import import="..." />` seems awkward, and translating `default as myfoo` to `import myfoo` seems less confusing when separated.)

For example:
```
<rt-import name="foo" from="mylib" />
<rt-import name="foo" as="myfoo" from="mylib" />
<rt-import name="*" as="myfoo" from="mylib" />
<rt-import name="default" as="myfoo" from="mylib" />
```

Which would translate respectively to:
```js
import {foo} from "mylib";
import {foo as myfoo} from "mylib";
import * as myfoo from "mylib";
import myfoo from "mylib";
```
This would be translated very similar to the behavior in this PR, and `rt-require` in its entirety can be still available but deprecated.

What do you think?

**Comment by nippur72** [comment]
ok, I can change it to `<rt-import>`, my only concern is that the result is not very readable.

What about this other syntax:
```html
<rt-import>
   {foo} from "mylib";
   {foo as myfoo} from "mylib";
   * as myfoo from "mylib";
   myfoo from "mylib";
</rt-import>
```
the advantage is that it mimics exactly the ES6 syntax, so no confusion at all. What do you think?

**Comment by steezeburger** [comment]
It's not quite as in line with RT's other syntax, but you are correct in that there is no confusion at all. I would have to refer to the documentation a lot for the former syntax, but either way I like both and just want the functionality!

**Comment by nippur72** [comment]
Ok, now I've split the syntax into `rt-require` and `rt-import` as per @ganimomer 's suggestion. 

`rt-require` works as before, `rt-import` supports the following:
```html
<rt-import name="foo" from="mylib" />
<rt-import name="foo" as="myfoo" from="mylib" />
<rt-import name="*" as="myfoo" from="mylib" />
<rt-import name="default" as="myfoo" from="mylib" />
```
when importing `*` or `default`, the `as` attribute is required.

**Comment by ganimomer** [comment]
Sorry for the holdup.
We've reviewed it and the current syntax (the one I suggested) is the one we accept.
I liked your suggestion, but I think we should still stick with a single import per statement, similar to `rt-require`.

**Comment by ganimomer** [comment]
Merged. New minor version to follow.

**Pull request merged**
