### PR TITLE
Adding <item>Pos in rt-repeat for working with 0 indexed position in the iteration

### PR DESCRIPTION
**Pull request by eberhm**
Hi there,
Fist of all, thanks a lot for the job done here... veeery neat! It saved my project.

I needed to add some incremental and reliable value (counter) in the iteration for functional testing purposes. That's why I've added this placeholder to the iterations.

Example:
<div rt-repeat="datum in dataObject">
    {datumIndex}
    {datum.propertyName} 
    {datumPos}
</div>

I believe this is a very common scenario when it comes down to have automated test suites for your site.

Hoping you find it useful...

### CODE REVIEW

**Comment by eberhm** [comment]
I've seen it did not pass the tests. Sorry about it. Tomorrow I'll get it fixed and will add some documentation.

**Comment by eberhm** [comment]
Tests passing and README.md modified to match current implementation

**Comment by eberhm** [comment]
Hi there,

Do you find this feature useful? Is there anything else needed?

Kind regards

**Comment by idok** [comment]
Hi,
Thanks for the PR.
If the map is on an array the index and position are the same, if it's an object you can get the postion by iterating the keys.
See example here:
http://wix.github.io/react-templates/fiddle.html#d2a445a8
Please let me know if this answers your use case

**Comment by eberhm** [comment]
Hi Idok,

That helped me out only in the case of iteration over an array. But iterations over objects could not be resolved using the same technique. That was the use case I faced. For these cases, changing the iterable for an indexed array with the former key as another property would work but with this feature, the template engine remains stable and yet more flexible since allows easy iterations over the two types (arrays and objects).

Thanks for your reply.

**Pull request closed without merging**
