### PR TITLE
Fix #167, #170 (react-native), #151, #152, #146

### LINKED ISSUE #167: native option in CLI does not work as expected
When using `react-templates` with `react-native` the docs say:

> In native mode the default modules option is set to commonjs and the default react-import-path is set to react-native.

But when using `--native` with the CLI the modules are not set to commonjs, nor the import path is set to `react-native`.

Here is the proof.

`tr template.rt --native` returns:
```js
var templateRT = function () {
    return React.createElement(React.View, {}, React.createElement(React.Text, {}, 'Hola'));
};
```

`tr template.rt --native --modules commonjs` returns:
```js
'use strict';
var React = require('react/addons');
var _ = require('lodash');
module.exports = function () {
    return React.createElement(React.View, {}, React.createElement(React.Text, {}, 'Hola'));
};
```

And finally `rt template.rt --modules commonjs --native --react-import-path react-native` returns:
```js
'use strict';
var React = require('react-native');
var _ = require('lodash');
module.exports = function () {
    return React.createElement(React.View, {}, React.createElement(React.Text, {}, 'Hola'));
};
```

### PR DESCRIPTION
**Pull request by nippur72**
This fixes #167. 

The problem was `--modules` defaulting to `none` from the command line, so that the right side of `||` was always ignored:
```js
finalOptions.modules = finalOptions.modules || (finalOptions.native ? 'commonjs' : 'none');
```
Similarly for `--react-import-path`.

The fix consists in avoiding the default values in `optionator` dependency, and managing them programmatically.

It's backward compatible when `--native` is not specified. When specified, it adheres to the specs (requires `react-native` and switches to commonjs).

### CODE REVIEW

**Comment by nippur72** [comment]
- Implemented the emitter for new `react-native` architecture (split between `react` and `react-native`, see #170)
- Added v`0.29.0` as new target for react native (default is still `0.9.0`).

**Comment by PierBover** [comment]
Awesome. Any idea when this PR will be merged?

**Comment by nippur72** [comment]
This PR now fixes #151 too.

Non breaking space appearing alone in a tag were trimmed out because the internal javascript `String.prototype.trim()` also trims non breaking spaces. 

I fixed it by writing a custom trim function that I use in place of the old one:
```js
function trimHtmlText(text) {
    return text.replace(/^[ \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+|[ \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]+$/g, '');
}
```

**Comment by nippur72** [comment]
This PR now fixes #152 too, checking that the only valid attributes for `<rt-virtual>` are `rt-if`, `rt-scope`, `rt-repeat`.

**Comment by nippur72** [comment]
This PR now fixes #171 too, checking that `rt-repeat` does not appear in a root node.

**Comment by nippur72** [comment]
This PR now implements #146 too, introducing the `--normalize-html-whitespace` CLI option.

When the option is turned on (default is off), all HTML text is passed thru [normalize-html-whitespace](https://github.com/stevenvachon/normalize-html-whitespace), removing all repeating whitespaces and saving bytes on the JavaScript output. 

Often the number of `React.createElement()` calls is reduced too.

Whitespace removal is applied on all tags except `<pre>` and `<textarea>` or when the special `rt-pre` attribute is specified.

**Comment by nippur72** [comment]
Thank you for merging :smile: 

The following issues related to this PR can be closed: #144, #157, #168.

These issues instead refer to other already merged PRs and can be closed too: #101, #111, #117.

**Pull request merged**
